### ISSUE TITLE
Dimension checking in `resample`

### ISSUE THREAD

**Issue by ariddell** [mattjj/pybasicbayes#18]
The following behavior caught me by surprise. Not entirely sure if it is intended.

```
K = 4
psi = np.ones(K)
beta = pybasicbayes.distributions.IsotropicGaussian(mu_0=np.zeros(K), nu_0=0.1, alpha_0=1, beta_0=1)
beta.resample(np.atleast_2d(psi))
beta.mu
beta.resample(psi[:, None])  # psi is (4, 1), seems like an error should be thrown.
beta.mu
```

Thanks for the library. This is great.

**Comment by mattjj** [comment]
Glad you like it! Some classes are more polished than others. Feedback is very welcome because I've been hoping to rewrite this library with a couple other interested parties.

**Comment by ariddell** [comment]
Further work/rewrites would be wonderful! I'm really attracted to the
idea of modularizing these "steps" in the Gibbs sampler.

I'd also love an example of a simple Gaussian hierarchical model (e.g.,
where mu_0 comes from the output of another Gaussian). Perhaps there's
already an idiom for this that I'm missing?

p.s. Is there any pybasicbayes-esque ARMS or slice sampler planned for
single (hyper) parameters? I could certainly use that.
