### ISSUE TITLE
Python 3 conversion incomplete

### ISSUE THREAD

**Issue by ariddell** [mattjj/pybasicbayes#21]
I realize I didn't deal with the difference in metaclass syntax. It looks like there's no trivial fix here. Would you be willing to accept a dependency on ``futurize`` (this seems to be the successor to ``six`` for writing 2&3 compatible code).

Here's the Python 2 and 3 compatible way to do metaclasses: http://python-future.org/compatible_idioms.html#metaclasses

**Comment by mattjj** [comment]
I must admit I've been merging without testing :)

I don't mind dependencies if they're pip-installable. Getting things to work with Python 3 has a much greater benefit than any minor cost from a dependency. Judging from the link, this would make the syntax kind of gross, but that seems fine too as long as it works!

Are you going to take a stab at it?

**Comment by ariddell** [comment]
Yes, I'll get something to you. I'll just use the with_metaclass dance.

**Comment by michaelpacer** [comment]
Any progress on this? I'm working on doing something similar with @slinderman's pyhawkes, and I think I'm running into some issues based on this dependency since it seems to run into unique errors regarding importing submodules when importing from pybasicbayes when running on python3 but not 2.

**Comment by ariddell** [comment]
Everything works under Python 3 right now. The abstractmethod isn't being enforced though. I'll try to finish this tomorrow.

**Comment by michaelpacer** [comment]
Excellent — thank you for this!

**Comment by mattjj** [comment]
Btw I pushed an updated version to pypi in the last few days.

**Comment by michaelpacer** [comment]
I noticed — that's why i was asking whether dependencies elsewhere should
be updated to require the newest version, but you explained that the
abstraction version should be backwards compatible which I trust you about.

**Comment by ariddell** [comment]
It looks like I added 'future' to the setup.py, so I think everything
should work.
