### ISSUE TITLE
Models folder is not copied during installation

### ISSUE THREAD

**Issue by dimarkov** [mattjj/pybasicbayes#31]
Hi!

For some reason the models folder is not copied to the installation path after running

python setup.py install

Best, 
Dima

**Comment by mattjj** [comment]
Good catch! It must be because it's [not listed in the `packages` argument of `setup`](https://github.com/mattjj/pybasicbayes/blob/master/setup.py#L59-L61). I'll push an attempt at a fix.

**Comment by mattjj** [comment]
That seems to have fixed it in my test. Please reopen if it's still broken.
